In [2]:
import sys
import time
import random

import numpy as np
import gym
import gym_chess
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("games.csv")

In [5]:
display(df.iloc[0]["moves"])

'd4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5 Bf4'

In [76]:

env = gym.make("ChessVsSelf-v1", log=False)

#
# Play against self
#
num_episodes = 2
num_steps = 100

total_steps = 0
collected_rewards = []
start = time.time()

[[-3 -5 -4 -2 -1 -4 -5 -3]
 [-6 -6 -6 -6 -6 -6 -6 -6]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 6  6  6  6  6  6  6  6]
 [ 3  5  4  2  1  4  5  3]]


In [77]:


for i in range(num_episodes):
    initial_state = env.reset()
    print("\n", "=" * 10, "NEW GAME", "=" * 10)
    env.render()
    total_rewards = {"WHITE": 0, "BLACK": 0}

    for j in range(num_steps):
      
        for 
        total_steps += 1
        # white moves
        moves = env.possible_moves
        m = random.choice(moves)
        a = env.move_to_action(m)
        # perform action
        state, reward, done, _ = env.step(a)
        total_rewards["WHITE"] += reward
        if done:
            break

        # black moves
        moves = env.possible_moves
        m = random.choice(moves)
        a = env.move_to_action(m)
        # perform action
        state, reward, done, _ = env.step(a)
        total_rewards["BLACK"] += reward
        if done:
            break

    print(">" * 5, "GAME", i, "REWARD:", total_rewards)
    collected_rewards.append(total_rewards)

[[array([6, 0], dtype=int8), array([5, 0], dtype=int8)], [array([6, 0], dtype=int8), array([4, 0], dtype=int8)], [array([6, 1], dtype=int8), array([5, 1], dtype=int8)], [array([6, 1], dtype=int8), array([4, 1], dtype=int8)], [array([6, 2], dtype=int8), array([5, 2], dtype=int8)], [array([6, 2], dtype=int8), array([4, 2], dtype=int8)], [array([6, 3], dtype=int8), array([5, 3], dtype=int8)], [array([6, 3], dtype=int8), array([4, 3], dtype=int8)], [array([6, 4], dtype=int8), array([5, 4], dtype=int8)], [array([6, 4], dtype=int8), array([4, 4], dtype=int8)], [array([6, 5], dtype=int8), array([5, 5], dtype=int8)], [array([6, 5], dtype=int8), array([4, 5], dtype=int8)], [array([6, 6], dtype=int8), array([5, 6], dtype=int8)], [array([6, 6], dtype=int8), array([4, 6], dtype=int8)], [array([6, 7], dtype=int8), array([5, 7], dtype=int8)], [array([6, 7], dtype=int8), array([4, 7], dtype=int8)], [array([7, 1], dtype=int8), array([5, 0], dtype=int8)], [array([7, 1], dtype=int8), array([5, 2], dtype

Action: 3364 is being passed to the environment.
           >>>>>>>>>> WHITE
    -------------------------
 8 |  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖ |
 7 |  ♙  ♙  ♙  ♙  ♙  ♙  ♙  ♙ |
 6 |  .  .  .  .  .  .  .  . |
 5 |  .  .  .  .  .  .  .  . |
 4 |  .  .  .  .  .  .  .  . |
 3 |  .  .  .  .  .  .  .  . |
 2 |  ♟  ♟  ♟  ♟  ♟  ♟  ♟  ♟ |
 1 |  ♜  ♞  ♝  ♛  ♚  ♝  ♞  ♜ |
    -------------------------
      a  b  c  d  e  f  g  h 
           >>>>>>>>>> BLACK
    -------------------------
 8 |  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖ |
 7 |  ♙  ♙  ♙  ♙  ♙  ♙  ♙  ♙ |
 6 |  .  .  .  .  .  .  .  . |
 5 |  .  .  .  .  .  .  .  . |
 4 |  .  .  .  .  ♟  .  .  . |
 3 |  .  .  .  .  .  .  .  . |
 2 |  ♟  ♟  ♟  ♟  .  ♟  ♟  ♟ |
 1 |  ♜  ♞  ♝  ♛  ♚  ♝  ♞  ♜ |
    -------------------------
      a  b  c  d  e  f  g  h 
New State: [[-3 -5 -4 -2 -1 -4 -5 -3]
 [-6 -6 -6  0 -6 -6 -6 -6]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 -6  0  0  0  0]
 [ 0  0  0  0  6  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 6  6  6  6  0  6  6  6]
 [ 3  5  4  2  1  4